### ISSUE TITLE
Required element to select doesn't work

### ISSUE THREAD

**Issue by DrowningElysium** [leocaseiro/angular-chosen#169]
I got a required single chosen field. But when pressing save and keeping it on the placeholder it just goes to the save page. This isn't what I want. When the chosen select is kept on the placeholder it should stay on the page.

**Comment by leocaseiro** [comment]
Chosen by itself don't work well with required because set the select with display:none.
I found a solution in one of chosen issue https://github.com/harvesthq/chosen/issues/515#issuecomment-33214050

it's kind of HACK, but works. So up to you, to use:

We add the class `.localytics-chosen` to all select chosen, so if you add the CSS:

```css
.localytics-chosen {
  display: block !important;
  position:absolute;
  clip:rect(0,0,0,0);
}
````

Set the required or ng-required if is dynamic and it will work just fine. Check my example on plunkr.

http://plnkr.co/edit/nF08ag?p=preview
