### ISSUE TITLE
Incompatibility with angular-dragdrop

### ISSUE THREAD

**Issue by andybak** [leocaseiro/angular-chosen#52]
Table rows with a 'chosen' select are invisible while dragging. Works when I remove the 'chosen' directive.

I also filed an issue there: https://github.com/angular-dragdrop/angular-dragdrop/issues/21

**Comment by leocaseiro** [comment]
Hi, first I'm really sorry for the delay. This project has a new maintainer (Read more #162)

I believe if we add this [CSS](https://github.com/leocaseiro/angular-chosen/issues/169#issuecomment-194815291), it might work. Have you tried?

```css
.localytics-chosen {
  display: block !important;
  position:absolute;
  clip:rect(0,0,0,0);
  height: 29px;
}
```

Could you please show me in a [plunkr](http://plnkr.co/edit/Zejg6f?p=preview) with this angular-dragdrop?
I'm not familiar with this directive, but I'm really interested in fix this issue.

Thanks.
