### ISSUE TITLE
Ng required doesn't work

### ISSUE THREAD

**Issue by CarlosCuevas** [leocaseiro/angular-chosen#87]
Console yields the error:
``
An invalid form control with name='example_name' is not focusable.
``

**Comment by alessani** [comment]
+1

**Comment by leocaseiro** [comment]
Sorry for my delay! I've just took this project that was abandoned (read #162).

I've fixed using CSS. Check if works for you.


```css
.localytics-chosen {
  display: block !important;
  position:absolute;
  clip:rect(0,0,0,0);
  height: 29px;
}
```
http://plnkr.co/edit/nF08ag?p=preview

Related to #169
